import { describe, expect, it } from "vitest";
import { sanitizeSvg } from "@/lib/tikz/sanitize";

const RAW = `<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 3.4.3 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='291.312139pt' height='156.294755pt' viewBox='-68.014948 -68.014949 291.312139 156.294755'>
<defs><path id='g0-65' d='M1 1'/></defs>
<g id='page1' onclick="alert(1)" onmouseover='x()'>
<script>alert(1)</script><script src="x.js"/>
<foreignObject><div>hi</div></foreignObject>
<a xlink:href="javascript:alert(2)"><use xlink:href='#g0-65'/></a>
</g>
</svg>
`;

describe("sanitizeSvg", () => {
  it("strips scripts, handlers, foreignObject, javascript: links, xml prolog and comments", () => {
    const { svg } = sanitizeSvg(RAW);
    expect(svg.startsWith("<svg")).toBe(true);
    expect(svg).not.toMatch(/<script/i);
    expect(svg).not.toMatch(/on(click|mouseover)/i);
    expect(svg).not.toMatch(/foreignObject/i);
    expect(svg).not.toMatch(/javascript:/i);
    expect(svg).toContain("<use xlink:href='#g0-65'/>");
    expect(svg).not.toContain("<?xml");
    expect(svg).not.toContain("<!--");
  });

  it("reads width/height in pt from the root, falling back to viewBox", () => {
    expect(sanitizeSvg(RAW)).toMatchObject({ width: 291.312139, height: 156.294755 });
    const r = sanitizeSvg("<svg viewBox='0 0 10 20'></svg>");
    expect(r).toMatchObject({ width: 10, height: 20 });
  });
});

describe("sanitizeSvg bypass shapes", () => {
  it("strips set/animate/style elements that can smuggle handlers or javascript hrefs", () => {
    const { svg } = sanitizeSvg("<svg><set attributeName='onclick' to='alert(1)'/><animate attributeName='href' values='javascript:x'></animate><animateTransform attributeName='transform'/><style>*{}</style><path d='M0 0'/></svg>");
    expect(svg).not.toMatch(/<set|<animate|<style/i);
    expect(svg).toContain("<path d='M0 0'/>");
  });
});
